include: 'http://build3.baylibre.com/ci/master/gitlab-ci-template.yml'

stages:
   - build

build_pages:
  stage: build
  image: python:3.7-alpine
  script:
  - wget --header="JOB-TOKEN:$CI_JOB_TOKEN" https://gitlab.com/api/v4/projects/8866061/packages/generic/intersphinx/1.0.0/objects.inv -O docs/bsp-objects.inv
  - pip install -U sphinx sphinx-rtd-theme sphinx-prompt
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
    refs:
    - merge_requests
    changes:
    - docs/**/*
