include: 'http://build3.baylibre.com/ci/master/gitlab-ci-template.yml'

stages:
   - build
   - deploy

build_pages:
  stage: build
  image: python:3.7-alpine
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html docs public
  only:
  - branches
  except:
  - master

deploy_pages:
  stage: deploy
  image: python:3.7-alpine
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - gatesgarth
